name: huggingface_dart
description: "Utilities to use the Hugging Face hub API"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.2
  dotenv: ^4.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0